<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'sp',
  'author' => 'chris olivo',
  'description' => 'sales package for sales transaction',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'sales_package',
  'published_date' => '2018-05-29 03:09:17',
  'type' => 'module',
  'version' => 1527563357,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'sales_package',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'sp_bank',
      'class' => 'sp_bank',
      'path' => 'modules/sp_bank/sp_bank.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'sp_Charges',
      'class' => 'sp_Charges',
      'path' => 'modules/sp_Charges/sp_Charges.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'sp_Color',
      'class' => 'sp_Color',
      'path' => 'modules/sp_Color/sp_Color.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'sp_Company',
      'class' => 'sp_Company',
      'path' => 'modules/sp_Company/sp_Company.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'sp_financingTerm',
      'class' => 'sp_financingTerm',
      'path' => 'modules/sp_financingTerm/sp_financingTerm.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'sp_invoiceVehichle',
      'class' => 'sp_invoiceVehichle',
      'path' => 'modules/sp_invoiceVehichle/sp_invoiceVehichle.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'sp_model',
      'class' => 'sp_model',
      'path' => 'modules/sp_model/sp_model.php',
      'tab' => true,
    ),
    7 => 
    array (
      'module' => 'sp_promoName',
      'class' => 'sp_promoName',
      'path' => 'modules/sp_promoName/sp_promoName.php',
      'tab' => true,
    ),
    8 => 
    array (
      'module' => 'sp_salesInvoice',
      'class' => 'sp_salesInvoice',
      'path' => 'modules/sp_salesInvoice/sp_salesInvoice.php',
      'tab' => true,
    ),
    9 => 
    array (
      'module' => 'sp_Scheme',
      'class' => 'sp_Scheme',
      'path' => 'modules/sp_Scheme/sp_Scheme.php',
      'tab' => true,
    ),
    10 => 
    array (
      'module' => 'sp_Site',
      'class' => 'sp_Site',
      'path' => 'modules/sp_Site/sp_Site.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_bank',
      'to' => 'modules/sp_bank',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_Charges',
      'to' => 'modules/sp_Charges',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_Color',
      'to' => 'modules/sp_Color',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_Company',
      'to' => 'modules/sp_Company',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_financingTerm',
      'to' => 'modules/sp_financingTerm',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_invoiceVehichle',
      'to' => 'modules/sp_invoiceVehichle',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_model',
      'to' => 'modules/sp_model',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_promoName',
      'to' => 'modules/sp_promoName',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_salesInvoice',
      'to' => 'modules/sp_salesInvoice',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_Scheme',
      'to' => 'modules/sp_Scheme',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sp_Site',
      'to' => 'modules/sp_Site',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);